name: Publish NightSky Listeners
on:
  push:
    branches: [main]
jobs:
  PublishMiddlewareExpress:
    runs-on: ubuntu-latest
    defaults:
      working-directory: middleware-express
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Increment version
        uses: copapow/version-bump-package@v1
          id: bump
          with:
              default_branch: main
              github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}