name: Test NightSky Listeners
on: [pull_request]
jobs:
  TestMiddlewareExpress:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: middleware-express
    defaults:
      run:
        working-directory: ${{env.WORKING_DIR}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
          cache: "npm"
          cache-dependency-path: ${{env.WORKING_DIR}}/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
