name: Test NightSky Listeners
on: [pull_request]
jobs:
  TestMiddlewareExpress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check out middleware-express directory
        run: cd middleware-express
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
